Todo_List/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Todo_List_App.urls'))
]

Todo_List_App/models.py
from django.contrib.auth.models import User, AbstractUser
from django.db import models
from django.utils import timezone


class Task(models.Model):
    taskTitle = models.CharField(max_length=100)
    category = models.ForeignKey('Category',related_name='tasks', on_delete=models.CASCADE , null=True)
    dueDate = models.DateTimeField()
    completed = models.BooleanField(default=False)
    completedDate = models.DateTimeField(null=True, blank=True)
    createdDate = models.DateTimeField(default=timezone.now())
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    important =models.BooleanField(default=False)

    def __str__(self):
        return self.taskTitle

class Category(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

class CompletedTask(models.Model):
    task = models.OneToOneField(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.task.taskTitle

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pictures', default='profile_pictures\default.jpg')
    completed_tasks_count = models.PositiveIntegerField(default=0)

    def update_completed_tasks_count(self):
        self.completed_tasks_count = self.user.task_set.filter(completed=True).count()
        self.save()

    def __str__(self):
        return self.user.username
    
class Solve(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()

Todo_List_App/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth.models import User
from .models import Profile
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth.models import User

class SignInForm(AuthenticationForm):
    pass

class SignUpForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('This username is already in use. Please choose a different one.')
        return username
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('This email address is already associated with an account.')
        return email
    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords do not match.")
        return cleaned_data

class ProfileForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = Profile
        fields = ['email', 'profile_picture']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['email'].initial = self.instance.user.email

    def save(self, commit=True):
        self.instance.user.email = self.cleaned_data['email']
        return super(ProfileForm, self).save(commit=commit)

class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label="New Password", widget=forms.PasswordInput)
    new_password2 = forms.CharField(label="Confirm New Password", widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if new_password1 != new_password2:
            raise forms.ValidationError("Passwords do not match.")
        
        return cleaned_data
    
class SolveForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()

templates/Sign_in.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In</title>
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: Arial, sans-serif;
        }
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .form {
            background-color: #fff;
            color: #000;
            padding: 30px;
            border-radius: 10px;
            max-width: 400px;
            text-align: center;
        }
        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            outline: none;
        }
        input[type="submit"] {
            background-color: #000;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }
        .signup_link {
            color: black;
            text-decoration: none;
        }
        .signup_link:hover {
            text-decoration: underline;
        }
        .alert-box {
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            font-weight: bold;
        }
        .alert-box.alert-danger {
            background-color: #ff0000;
            color: #ffffff;
            border: 2px solid #ff0000;
        }
        .alert-box.alert-success {
            background-color: #00ff00;
            color: #ffffff;
            border: 2px solid #00ff00;
        }
    </style>
</head>
<body>
    <div class="container">
        <form class="form" method="post" action="{% url 'signin' %}">
            {% csrf_token %}
            <h2>Login</h2>
            <input type="text" name="username" placeholder="Username" required>
            <input type="password" name="password" placeholder="Password" required>
            <input type="checkbox" name="remember_me" id="remember_me">
            <label for="remember-me" align="right">Remember me</label><br>
            <input type="submit" value="Login">
            <p>Don't have an account? <a href="{% url 'signup' %}"><b>Sign up</b></a></p>
            <p><a href="{% url 'forgot_password' %}" class="link">Forgot password?</a></p>
            {% if messages %}
                <div class="text-center mt-3">
                    {% for message in messages %}
                        <div class="alert-box {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% else %}alert-success{% endif %}">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </form>
    </div>
</body>
</html>

templates/Sign_up.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <style>
        body {
            background-color: #000;
            color: #fff;
            font-family: Arial, sans-serif;
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .form {
            background-color: #fff;
            color: #000;
            padding: 30px;
            border-radius: 10px;
            max-width: 400px;
            text-align: center;
        }

        input[type="text"],
        input[type="email"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            outline: none;
        }

        input[type="submit"] {
            background-color: #000;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }
        .signup_link {
            color: black;
            text-decoration: none;
        }
        .signup_link:hover {
            text-decoration: underline;
        }
        .alert-box {
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            font-weight: bold;
        }
        .alert-box.alert-danger {
            background-color: #ff0000;
            color: #ffffff; 
            border: 2px solid #ff0000;
        }
        .alert-box.alert-success {
            background-color: #00ff00;
            color: #ffffff; 
            border: 2px solid #00ff00;
        }
    </style>
</head>
<body>
    <div class="container">
        <form class = "form" method = "post">
            <h2>Sign up</h2>
            {% csrf_token %}
                <input type="text" name="username" placeholder="Username" required>
                {% if form.username.errors %}
                    <div class="error">{{ form.username.errors }}</div>
                {% endif %}
                <input type="email" name="email" placeholder="Email" required>
                {% if form.email.errors %}
                    <div class="error">{{ form.email.errors }}</div>
                {% endif %}
                <input type="password" name="password1" placeholder="Password" required>
                <input type="password" name="password2" placeholder="Confirm Password" required>
                {% if form.password2.errors %}
                    <div class="error">{{ form.password2.errors }}</div>
                {% endif %}
            <input type="submit" value="Sign Up">
            <p>Already have an account? <a href="{% url 'signin' %}"><b>Sign in</b></a></p>
            {% if messages %}
            <div class="text-center mt-3">
                {% for message in messages %}
                    <div class="alert-box {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
            {% endif %}
        </form>
    </div>
</body>
</html>

templates/add_category.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ADD CATEGORY - TODO LIST</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'base.html' %}
<div class="container my-3">
    <h3 class="text-center">Add Category</h3>
    <form method="POST" action="/add-category/">
        {% csrf_token %}
        <div class="mb-3">
            <label for="category" class="form-label">Category Name :</label>
            <input type="text" class="form-control" id="category" name="name" placeholder="EX : HOME" required>
        </div>
        <button type="submit" class="btn btn-primary btn-add">Add</button>
    </form>
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger mt-3 text-center" role="alert"text-center>
                    {{ message }}
                </div>
            {% endif %}
            {% if message.tags == 'success' %}
            <div class="alert alert-success mt-3 text-center" role="alert" text-center>
                Category created successfully! Lets <a href="{% url 'Todo_List_App' %}" class="alert-link"style="color:green;"> Create a Task</a>
            </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

templates/all_categories.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ALL CATEGORY - TODO LIST</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'base.html' %}
<div class="container my-3">
    <div class="heading-container">
        <h3 class="text-center">All Categories</h3><br>
    </div>
    <div id="category-accordion">
        {% for category in categories %}
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center mode"id="category-heading-{{ category.id }}">
                <h5 class="mb-0">
                    <button class="btn btn-link category-name" data-toggle="collapse" data-target="#category-collapse-{{ category.id }}" aria-expanded="true" aria-controls="category-collapse-{{ category.id }}">
                        {{ category.name }} : [{{ category.tasks.count }}]
                    </button>
                </h5>
                <a href="{% url 'delete_category' category.id %}" class="btn btn-danger btn-sm delete-link">Delete</a>
            </div>

            <div id="category-collapse-{{ category.id }}" class="collapse" aria-labelledby="category-heading-{{ category.id }}" data-parent="#category-accordion">
                <div class="card-body mode">
                    <table class="table table-hover">
                        <thead>
                            <tr class="table-dark">
                                <th scope="col">Title</th>
                                <th scope="col">Created Date</th>
                                <th scope="col">Due/Completed Date</th>
                                <th scope="col">Priority</th>
                                <th scope="col">Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for task in category.tasks.all|dictsortreversed:"important" %}
                            <tr>
                                <td>{{ task.taskTitle }}</td>
                                <td>{{ task.createdDate |date:'d - m - y | h:i A' }}</td>
                                <td>
                                    {% if task.completed %}
                                    {{ task.completedDate |date:'d - m - y | h:i A' }}
                                    {% else %}
                                    {{ task.dueDate |date:'d - m - y | h:i A' }}
                                    {% endif %}
                                </td>
                                <td>{% if task.important %}Important{% else %}Not Important{% endif %}</td>
                                <td> {% if task.completed %}Completed{% else %}Running{% endif %}</td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="5"align="center"><h5>No tasks available for this category.</h5></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% endfor %}
        {% if no_categories %}
        <div class="alert alert-info mt-3" role="alert">
            No categories available. Create a category to proceed.
        </div>
        {% endif %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
    $(document).ready(function() {
        $('.collapse').removeClass('show');
        $('.btn-link').click(function() {
            $(this).toggleClass('collapsed');
            var target = $(this).data('target');
            $(target).collapse('toggle');
        });
    });
</script>
</body>
</html>

templates/base.html
<div class="text-end at-the-end-of-text-Dark_mode">
    <div class="form-check form-switch">
        <label class="form-check-label" for="themeSwitch">Reading Mode</label>
        <input class="form-check-input" type="checkbox" id="themeSwitch">
    </div>
</div>



<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/todo">TO-DO</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link active" aria-current="page" href="/home">Home</a>
                    {% else %}
                        <a class="nav-link active" aria-current="page" href="/signin">Home</a>
                    {% endif %}
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Tasks
                    </a>
                    <ul class="dropdown-menu">
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="dropdown-item" aria-current="page" href="/running-tasks">Running</a>
                            {% else %}
                                <a class="dropdown-item" aria-current="page" href="/signin">Running</a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="dropdown-item" aria-current="page" href="/completed-tasks">Completed</a>
                            {% else %}
                            <a class="dropdown-item" aria-current="page" href="/signin">Completed</a>
                            {% endif %}
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Category
                    </a>
                    <ul class="dropdown-menu">
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="dropdown-item" aria-current="page" href="/add-category">Add Category</a>
                            {% else %}
                                <a class="dropdown-item" aria-current="page" href="/signin">Add Category</a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="dropdown-item" aria-current="page" href="/all-categories">All Categories</a>
                            {% else %}
                                <a class="dropdown-item" aria-current="page" href="/signin">All Categories</a>
                            {% endif %}
                        </li>
                    </ul>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                {% if user.is_authenticated %}
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                        <li>
                            <div class="dropdown-header">
                                <img src="{{ user.profile.profile_picture.url }}" class="rounded-circle" width="30" height="30" alt="Profile Picture">
                                {{ user.username }}
                            </div>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <a class="dropdown-item" href="{% url 'profile' %}">
                                <i class="bi bi-person"></i>
                                Account
                            </a>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <a class="dropdown-item" href="https://github.com/HarshitS45">
                                <i class="bi bi-envelope"></i>About
                            </a>
                        </li> 
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <a class="dropdown-item" href="{% url 'logout' %}">
                                <i class="bi bi-box-arrow-right"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                {% else %}
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        User
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <a class="dropdown-item" href="/signin">
                                <i class="bi bi-person"></i>
                                    Sign In
                            </a>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                            <li>
                            <a class="dropdown-item" href="/signup">
                                <i class="bi bi-envelope"></i>
                                    Sign Up
                            </a>
                        </li>
                    </ul>
                {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

<script>
    const darkModePref = localStorage.getItem('darkMode');
    if (darkModePref === 'true') {
        document.body.classList.add('dark-mode');
        document.getElementById('themeSwitch').checked = true;
    }
    document.getElementById('themeSwitch').addEventListener('change', function () {
        if (this.checked) {
            document.body.classList.add('dark-mode');
            localStorage.setItem('darkMode', true);
        } else {
            document.body.classList.remove('dark-mode');
            localStorage.setItem('darkMode', false);
        }
    });
</script>

templates/profile.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Profile</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'base.html' %}
    <div class="profile-section">
        <div class="profile-picture">
            <img src="{{ user.profile.profile_picture.url }}" class="rounded-circle" width="200" height="200" alt="Profile Picture">
        </div>
        <div class="profile-details">
            <h3 class="username">{{ user.username }}</h3>
            <p class="completed-tasks">Total Completed Tasks : {{ user.profile.completed_tasks_count }}</p>
        </div>
    </div>
    
    <div class="container my-3">
        <h2 class="text-center">Profile</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_profile_picture" class="form-label" style="margin-top: 50px">Profile Picture:</label>
                <input type="file" class="form-control" name="profile_picture" id="id_profile_picture">
                {% if form.profile_picture.errors %}
                    <div class="errors">
                        {% for error in form.profile_picture.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="id_email" class="form-label">Email:</label>
                <input type="email" class="form-control" name="email" id="id_email" value="{{ form.email.value }}">
                {% if form.email.errors %}
                    <div class="errors">
                        {% for error in form.email.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label for="change_password" class="form-label">Change Password:</label>
                <select class="form-select" name="change_password" id="change_password">
                    <option value="no_change">No Change</option>
                    <option value="change">Change Password</option>
                </select>
            </div>
            <div id="password_fields" style="display: none;">
                <div class="mb-3">
                    <label for="id_old_password" class="form-label">Old Password:</label>
                    <input type="password" class="form-control" name="old_password" id="id_old_password">
                    {% if password_form.old_password.errors %}
                        <div class="errors">
                            {% for error in password_form.old_password.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_new_password1" class="form-label">New Password:</label>
                    <input type="password" class="form-control" name="new_password1" id="id_new_password1">
                    {% if password_form.new_password1.errors %}
                        <div class="errors">
                            {% for error in password_form.new_password1.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="id_new_password2" class="form-label">Confirm New Password:</label>
                    <input type="password" class="form-control" name="new_password2" id="id_new_password2">
                    {% if password_form.new_password2.errors %}
                        <div class="errors">
                            {% for error in password_form.new_password2.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <button type="submit" class="btn btn-primary btn-add" style = "background-color:#0DBEF3;">Save</button>
        </form>
        <br>
        <form method="POST" action="{% url 'delete_account' user.id %}">
            {% csrf_token %}
            <div class="mb-3">
                <label for="confirm" class="form-label">Option :</label>
                <select class="form-select" name="confirm" id="confirm">
                    <option value="no_change">No Change</option>
                    <option value="delete_account">DELETE  ACCOUNT</option>
                </select>
            </div>
            <div id="delete_account" style="display: none;">
                <div class="mb-3">
                    <label for="confirm" class="form-label" style="color:#EC7063;">WARNING : This action can't be reversed, type "CONFIRM" to delete account.</label>
                    <input type="text" class="form-control" name="confirm" id="confirm">
                </div>
            </div>
            <button type="submit" class="btn btn-danger">Delete Account</button>
        </form>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        $(document).ready(function() {
            $("#change_password").change(function() {
                var passwordFields = $("#password_fields");
                console.log($(this).val())
                if ($(this).val() === "change") {
                    passwordFields.show();
                    passwordFields.find("input").prop("required", true);
                } else {
                    passwordFields.hide();
                    passwordFields.find("input").prop("required", false);
                }
            });
        });
    </script>
    <script>
        $(document).ready(function() {
            $("#confirm").change(function() {
                var deleteAccount = $("#delete_account");
                console.log($(this).val())
                if ($(this).val() === "delete_account") {
                    deleteAccount.show();
                    deleteAccount.find("input").prop("required", true);
                } else {
                    deleteAccount.hide();
                    deleteAccount.find("input").prop("required", false);
                }
            });
        });
    </script>
</body>
</html>